spring:
  application:
    name: kiosco
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 4
      minimun-idle: 2
      connection-timeout: 600000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 8083
logging:
  level:
    root: INFO
    com.kiosco: DEBUG
    org.springframework.web: INFO
springdoc:
  pageable:
    support-page-request: true
  default-support-page-request: true
app:
  storage:
    categorias-path: "./data/categorias.json"
    marcas-path: "./data/marcas.json"
