spring:
  application:
    name: kiosco
  datasource:
    url: jdbc:sqlite:kiosco.db?journal_mode=WAL&busy_timeout=5000
    hikari:
      maximum-pool-size: 1
    username:
    password:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 8083
logging:
  level:
    root: INFO
    com.kiosco: DEBUG
    org.springframework.web: INFO
springdoc:
  pageable:
    support-page-request: true
  default-support-page-request: true
app:
  storage:
    categorias-path: "./data/categorias.json"
    marcas-path: "./data/marcas.json"